### PR TITLE
V1/pipeline generator/pipeline menu #10

### LINKED ISSUE #10: As a user I want to be able to generate Pipeline, and listing the selected options
Como usuario quiero poder generar Pipeline , en listando las opciones seleccionadas

### PR DESCRIPTION
**Pull request by rolzing**
closes #10 

[daily.docx](https://github.com/DigitalOnUs/jenkins-dashboard/files/1726234/daily.docx)

### CODE REVIEW

**Comment by rolzing** [comment]
[daily.docx](https://github.com/DigitalOnUs/jenkins-dashboard/files/1726216/daily.docx)

**Comment by thetonymaster** [comment]
- Next time you do a PR include screenshots of the flow (you can use something like imgur) 
- Why did you uploadad a daily here? create a folder in one drive or google drive to store them.
- I recommended you to use api blueprint to create a mock server
- I thought we will create the specification first, then we would continue with the mockups
- I can't see if I can edit an already generated pipeline
- Change add row to Add Step
- Can I configure each step independently?
- Do not use *minor fix* state what was fixed

**Comment by rolzing** [comment]
-Main preview
image
-Add step form
image
image
-List of steps
image
image
image
-Remove
image
image

**Comment by thetonymaster** [comment]
Good job, just as agreed yesterday, instead of putting a name such as `CI_SOMETHING_SOMETHIN` use human readable names, like `Continuous Integration`

**Comment by rolzing** [comment]
Add last changes for Pipeline Generator view. 

#10
@thetonymaster

**Comment by MiguelRomero** [comment]
It's ready to deploy @rolzing 🗡

**Pull request merged**
